apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: read-files-template
spec:
  entrypoint: read-files
  arguments:
    parameters:
    - name: base-url
    - name: record-id
    - name: file-ids
    - name: secret-key
  templates:
  - name: read-files
    inputs:
      parameters:
      - name: base-url
      - name: record-id
      - name: secret-key
      - name: file-ids
    container:
      image: xkollar173/argo-read-files:0.0.8
      command: [sh, "-c"]
      args:
        - |
          ./read-files.sh "{{inputs.parameters.base-url}}" "{{inputs.parameters.record-id}}" "{{inputs.parameters.secret-key}}" "{{inputs.parameters.file-ids}}"
    outputs:
      artifacts:
      - name: output-files
        path: /output
