apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: download-files-template
spec:
  entrypoint: download-files
  arguments:
    parameters:
    - name: base-url
    - name: record-id
    - name: file-ids
  templates:
  - name: download-files
    inputs:
      parameters:
      - name: base-url
      - name: record-id
      - name: file-ids
    container:
      image: xkollar173/argo-read-files:0.0.3 
      command: [sh, "-c"]
      args:
        - |
          ./read-files.sh "{{inputs.parameters.base-url}}" "{{inputs.parameters.record-id}}" "{{inputs.parameters.file-ids}}" 
    outputs:
      artifacts:
      - name: downloaded-files
        path: /files 
