server:
  host: localhost
  port: 8062

context-path: "/api"

argo-workflows:
  url: https://localhost:2746
  namespace: "argo"

compchem:
  url: https://host-service.argo.svc.cluster.local:5000/api/experiments

workflows:
  - name: count-words
    filetype: txt
    processing-templates:
      - name: count-words-template
        template: count-words
