apiVersion: v1
kind: Service
metadata:
  name: {{ include "compchem-helm-chart.fullname" . }}-fileprocessor
  labels:
    {{- include "compchem-helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: fileprocessor
spec:
  type: {{ .Values.fileprocessor.service.type }}
  ports:
    - port: {{ .Values.fileprocessor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.fileprocessor.service.type "NodePort") .Values.fileprocessor.service.nodePort }}
      nodePort: {{ .Values.fileprocessor.service.nodePort }}
      {{- end }}
  selector:
    {{- include "compchem-helm-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: fileprocessor
