apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fileprocessor.fullname" . }}-config
  labels:
    {{- include "fileprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: fileprocessor
data:
  application.yaml: |
    server:
      host: {{ .Values.server.host }}
      port: {{ .Values.server.port }}
    context-path: {{ .Values.server.contextPath | quote }}
    argo-workflows:
      url: {{ .Values.argoWorkflows.url }}
      namespace: {{ .Values.argoWorkflows.namespace | quote }}
    compchem:
      url: {{ .Values.compchem.url }}
    migrations: {{ .Values.migrations | quote }}
    postgres:
      host: {{ .Values.postgres.host }}
      port: {{ .Values.postgres.port }}
      database: {{ .Values.postgres.database }}
      auth:
        user: {{ .Values.postgres.auth.user }}
    {{- if .Values.workflows }}
    workflows:
      {{- toYaml .Values.workflows | nindent 6 }}
    {{- else }}
    workflows: []
    {{- end }}
