apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fileprocessor.fullname" . }}
  labels:
    {{- include "fileprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: fileprocessor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fileprocessor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: fileprocessor
  template:
    metadata:
      labels:
        {{- include "fileprocessor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fileprocessor
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fileprocessor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fileprocessor.fullname" . }}-secret
                  key: postgres-password
          volumeMounts:
            - name: config
              mountPath: /app/server-config.yaml
              subPath: server-config.yaml
              readOnly: true
          livenessProbe:
            httpGet:
              path: {{ .Values.server.contextPath }}/v1/health/liveness
              port: 8062
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.server.contextPath }}/v1/health/readiness
              port: 8062
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fileprocessor.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
