apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fileprocessor.fullname" . }}-secret
  labels:
    {{- include "fileprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: fileprocessor
type: Opaque
data:
  postgres-password: {{ .Values.postgres.auth.password | b64enc | quote }}
