apiVersion: v1
kind: Service
metadata:
  name: {{ include "fileprocessor.fullname" . }}
  labels:
    {{- include "fileprocessor.labels" . | nindent 4 }}
    app.kubernetes.io/component: fileprocessor
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: fileprocessor
