apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: write-files-template
spec:
  entrypoint: write-files
  arguments:
    parameters:
      - name: base-url
      - name: record-id
      - name: workflow-name
      - name: task-discriminator
    artifacts:
      - name: input-files
  templates:
    - name: write-files
      inputs:
        parameters:
          - name: base-url
          - name: record-id
          - name: workflow-name
          - name: task-discriminator
        artifacts:
          - name: input-files
            path: /input
      container:
        image: xkollar173/argo-write-files:0.0.4
        command: [sh, "-c"]
        args:
          - ./write-files.sh "{{inputs.parameters.base-url}}" "{{inputs.parameters.record-id}}" "{{inputs.parameters.workflow-name}}" "{{inputs.parameters.task-discriminator}}"
