package argodtos

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
)

// templated by me generated by claude AI
func TestReadFiles_AllArgumentsSupplied_ProperlyFormedTask(t *testing.T) {
	// Arrange
	recordId := "recordId"
	workflowId := "workflowId"
	expectedName := fmt.Sprintf(ReadFilesTemplate, recordId, workflowId)
	expectedDependencies := []string{}
	expectedTemplateRefName := "read-files-template"
	expectedTemplateRefTemplate := "read-files"

	// Act
	task := NewReadFilesWorkflow(recordId, workflowId)

	// Assert
	assert.Equal(t, expectedName, task.Name)
	assert.Equal(t, expectedDependencies, task.Dependencies)
	assert.Equal(t, expectedTemplateRefName, task.TemplateReference.Name)
	assert.Equal(t, expectedTemplateRefTemplate, task.TemplateReference.Template)

	// Verify parameters
	assert.Equal(t, 3, len(task.Arguments.Parameters))

	// Check each parameter
	assert.Equal(t, "base-url", task.Arguments.Parameters[0].Name)
	assert.Equal(t, "{{workflow.parameters.base-url}}", task.Arguments.Parameters[0].Value)

	assert.Equal(t, "record-id", task.Arguments.Parameters[1].Name)
	assert.Equal(t, "{{workflow.parameters.record-id}}", task.Arguments.Parameters[1].Value)

	assert.Equal(t, "file-ids", task.Arguments.Parameters[2].Name)
	assert.Equal(t, "{{workflow.parameters.file-ids}}", task.Arguments.Parameters[2].Value)
}

func TestReadFiles_AllArgumentsSupplied_ProperlyFormedJson(t *testing.T) {
	// Arrange
	recordId := "recordId"
	workflowId := "workflowId"
	task := NewReadFilesWorkflow(recordId, workflowId)

	// Act
	taskJson, err := json.Marshal(task)

	// Assert
	assert.NoError(t, err)

	// Define expected JSON
	expectedJson := `{
		"name": "read-files-recordId-workflowId",
		"dependencies": [],
		"templateRef": {
			"name": "read-files-template",
			"template": "read-files"
		},
		"arguments": {
			"artifacts": [],
			"parameters": [
				{
					"name": "base-url",
					"value": "{{workflow.parameters.base-url}}"
				},
				{
					"name": "record-id",
					"value": "{{workflow.parameters.record-id}}"
				},
				{
					"name": "file-ids",
					"value": "{{workflow.parameters.file-ids}}"
				}
			]
		}
	}`

	// Normalize both JSON strings for comparison (remove whitespace differences)
	var expected, actual any
	err = json.Unmarshal([]byte(expectedJson), &expected)
	assert.NoError(t, err)

	err = json.Unmarshal(taskJson, &actual)
	assert.NoError(t, err)

	// Re-marshal both to normalized format
	expectedNormalized, err := json.Marshal(expected)
	assert.NoError(t, err)

	actualNormalized, err := json.Marshal(actual)
	assert.NoError(t, err)

	// Compare the normalized JSON strings
	assert.Equal(t, string(expectedNormalized), string(actualNormalized))
}
