version: "3.8"

services:
  backend:
    image: compchem-fileprocessor # TODO: tags, cerit repo?
    container_name: compchem-fileprocessor-api
    restart: always
    ports:
      - "8062:8062"
    volumes:
      - ./server-config.yaml:/app/server-config.yaml
  db:
    image: "postgres:17"
    container_name: fileprocessor-database
    restart: always
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: fileprocessor
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fileprocessor
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
