apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "compchem-helm-chart.fullname" . }}-compchem-config
  labels:
    {{- include "compchem-helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: compchem
data:
  {{- if .Values.compchem.database.enabled }}
  # Database Configuration
  INVENIO_DATABASE_HOST: {{ .Values.compchem.database.host }}
  INVENIO_DATABASE_PORT: {{ .Values.compchem.database.port | quote }}
  INVENIO_DATABASE_DBNAME: {{ .Values.compchem.database.name }}
  INVENIO_DATABASE_USER: {{ .Values.compchem.database.user }}
  {{- end }}

  {{- if .Values.compchem.redis.enabled }}
  # Redis Configuration
  INVENIO_REDIS_HOST: {{ .Values.compchem.redis.host }}
  INVENIO_REDIS_PORT: {{ .Values.compchem.redis.port | quote }}
  {{- end }}

  {{- if .Values.compchem.rabbitmq.enabled }}
  # RabbitMQ Configuration
  INVENIO_RABBIT_HOST: {{ .Values.compchem.rabbitmq.host }}
  INVENIO_RABBIT_PORT: {{ .Values.compchem.rabbitmq.port | quote }}
  INVENIO_RABBIT_ADMIN_PORT: {{ .Values.compchem.rabbitmq.adminPort | quote }}
  INVENIO_RABBIT_USER: {{ .Values.compchem.rabbitmq.user }}
  {{- end }}

  {{- if .Values.compchem.opensearch.enabled }}
  # OpenSearch Configuration
  INVENIO_OPENSEARCH_HOST: {{ .Values.compchem.opensearch.host }}
  INVENIO_OPENSEARCH_PORT: {{ .Values.compchem.opensearch.port | quote }}
  INVENIO_OPENSEARCH_CLUSTER_PORT: {{ .Values.compchem.opensearch.clusterPort | quote }}
  {{- end }}

  {{- if .Values.compchem.s3.enabled }}
  # S3/MinIO Configuration
  INVENIO_S3_HOST: {{ .Values.compchem.s3.host }}
  INVENIO_S3_PORT: {{ .Values.compchem.s3.port | quote }}
  INVENIO_S3_PORT1: {{ .Values.compchem.s3.consolePort | quote }}
  INVENIO_S3_BUCKET: {{ .Values.compchem.s3.bucket }}
  INVENIO_S3_ENDPOINT_URL: {{ .Values.compchem.s3.endpointUrl }}
  {{- end }}

  # Application Configuration
  INVENIO_INSTANCE_PATH: {{ .Values.compchem.instancePath }}
  INVENIO_STATIC_FOLDER: {{ .Values.compchem.staticFolder }}
  INVENIO_THEME: {{ .Values.compchem.theme }}
  FLASK_ENV: {{ .Values.compchem.flaskEnv }}
  INVENIO_SECRET_KEY_FILE: "/etc/invenio/secrets/secret-key"

  # Server Configuration
  INVENIO_WSGI_MODULE: "invenio_app.wsgi:application"
  INVENIO_WSGI_PROCESSES: {{ .Values.compchem.wsgi.processes | quote }}
  INVENIO_WSGI_THREADS: {{ .Values.compchem.wsgi.threads | quote }}

  # SSL Configuration
  INVENIO_TLS_CERT_FILE: "/etc/ssl/certs/tls.crt"
  INVENIO_TLS_KEY_FILE: "/etc/ssl/private/tls.key"
