apiVersion: v1
kind: Service
metadata:
  name: host-service
  namespace: argo
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Endpoints
metadata:
  name: host-service
  namespace: argo
subsets:
- addresses:
  - ip: 172.17.0.1  # Your host IP as seen from the container
  ports:
  - port: 5000

