apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: read-count-write-ew6jd-p8175-1
spec:
  entrypoint: read-count-write
  arguments:
    parameters:
    - name: base-url
      value: https://host-service.argo.svc.cluster.local:5000/api/experiments
    - name: file-ids
      value: test-count.txt 
    - name: record-id
      value: ew6jd-p8175 

  templates:
  - name: read-count-write
    dag:
      tasks:
      - name: read-files-12345-2
        templateRef:
          name: download-files-template
          template: download-files
        arguments:
          parameters:
          - name: base-url
            value: "{{workflow.parameters.base-url}}"
          - name: record-id
            value: "{{workflow.parameters.record-id}}"
          - name: file-ids
            value: "{{workflow.parameters.file-ids}}"

      - name: count-words-12345-2 
        dependencies: [read-files-12345-2]
        templateRef:
          name: count-words-template 
          template: count-words
        arguments:
          artifacts:
            - name: input-files
              from: "{{tasks.read-files-12345-2.outputs.artifacts.output-files}}"

      - name: write-files-12345-2
        dependencies: [count-words-12345-2]
        templateRef:
          name: write-files-template 
          template: upload-files 
        arguments:
          parameters:
          - name: base-url
            value: "{{workflow.parameters.base-url}}"
          - name: record-id
            value: "{{workflow.parameters.record-id}}"
          artifacts:
          - name: input-files 
            from: "{{tasks.count-words-12345-2.outputs.artifacts.output-files}}"
